In [ ]:
#Regression
import pandas as pd
from sklearn.linear_model import LinearRegression

In [ ]:
df = pd.DataFrame({'x1':[1,2,3,4],'y':[2,4,6,8]})
df.head()

x1  y
0   1  2
1   2  4
2   3  6
3   4  8

In [ ]:
x = df[['x1']]
y = df['y']

In [ ]:
lr = LinearRegression()
lr.fit(x,y)

LinearRegression()

In [ ]:
lr.predict([[5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([10.])

In [ ]:
lr.coef_

array([2.])

In [ ]:
lr.coef_

array([2.])

In [ ]:
lr.score(x,y) *100

100.0

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.datasets import fetch_california_housing

In [ ]:
california_data = fetch_california_housing()

In [ ]:
california_data

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [ ]:
df = pd.DataFrame(data=california_data.data,columns=california_data.feature_names )

In [ ]:
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [ ]:
df['price'] = california_data.target
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  price  
0    -122.23  4.526  
1    -122.22  3.585  
2    -122.24  3.521  
3    -122.25  3.413  
4    -122.25  3.422

In [ ]:
X = df[[]]
y = df['price']

In [ ]:
X = df.drop('price',axis=1)
y = df['price']

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 50)

In [ ]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
model.predict([[8.3252,41.0,	6.984127	,1.023810,	322.0	,2.555556,	37.88	,-122.23	]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4.12394841])

In [ ]:
model.predict(pd.DataFrame({'MedInc':[8.3252],'HouseAge':[41.0],'AveRooms':[6.984127],'AveBedrms':[1.023810],'Population':[322.0],'AveOccup':[2.555556],'Latitude':[37.88],'Longitude':[-122.23]}))

array([4.12394841])

In [ ]:
model.score(X_train,y_train) * 100

60.6327052393095

In [ ]:
#Classification
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix

In [ ]:
df = pd.read_csv('iris.csv', names=['sepal_length',	'sepal_width',	'petal_length',	'petal_width',	'species'])
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
df.shape

(150, 5)

In [ ]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [ ]:
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df['species']

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=32)

In [ ]:
lgr = LogisticRegression(max_iter=300)
lgr.fit(X_train,y_train)

LogisticRegression(max_iter=300)

In [ ]:
y_pred = lgr.predict(X_test)

In [ ]:
accuracy_score(y_test,y_pred)

1.0

In [ ]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0,  9,  0],
       [ 0,  0,  9]])

In [ ]:
df1 = pd.DataFrame({'actualvalues':y_test,'predictedvalues':y_pred})
df1

actualvalues  predictedvalues
55   Iris-versicolor  Iris-versicolor
22       Iris-setosa      Iris-setosa
26       Iris-setosa      Iris-setosa
56   Iris-versicolor  Iris-versicolor
134   Iris-virginica   Iris-virginica
131   Iris-virginica   Iris-virginica
23       Iris-setosa      Iris-setosa
34       Iris-setosa      Iris-setosa
85   Iris-versicolor  Iris-versicolor
21       Iris-setosa      Iris-setosa
76   Iris-versicolor  Iris-versicolor
115   Iris-virginica   Iris-virginica
60   Iris-versicolor  Iris-versicolor
67   Iris-versicolor  Iris-versicolor
147   Iris-virginica   Iris-virginica
113   Iris-virginica   Iris-virginica
66   Iris-versicolor  Iris-versicolor
123   Iris-virginica   Iris-virginica
69   Iris-versicolor  Iris-versicolor
10       Iris-setosa      Iris-setosa
44       Iris-setosa      Iris-setosa
107   Iris-virginica   Iris-virginica
138   Iris-virginica   Iris-virginica
12       Iris-setosa      Iris-setosa
13       Iris-setosa      Iris-setosa
95   Iris-versicolor  Iris-versicolor
16       Iris-setosa      Iris-setosa
140   Iris-virginica   Iris-virginica
27       Iris-setosa      Iris-setosa
39       Iris-setosa      Iris-setosa

In [ ]:
lgr.predict([[5.1	,3.5	,1.4	,0.2	]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array(['Iris-setosa'], dtype=object)